export const SEED_PATIENTS = [
  {
    id: 'pat-101',
    abhaId: '91-4521-8890-1200',
    name: 'Ramesh Tukaram Patil',
    nameMr: 'रमेश तुकाराम पाटील',
    age: 48,
    gender: 'male',
    phone: '+91 98500 44332',
    address: 'House No. 42, Vetal Pada, Paud Village',
    village: 'Paud',
    taluka: 'Mulshi',
    district: 'Pune',
    pincode: '412108',
    bloodGroup: 'B+',
    allergies: ['Penicillin', 'Sulfa Drugs'],
    chronicConditions: ['Hypertension', 'Type 2 Diabetes Mellitus'],
    emergencyContact: {
      name: 'Sunita Ramesh Patil',
      relationship: 'Spouse',
      phone: '+91 98500 44333',
    },
    vitals: {
      bpSystolic: 146,
      bpDiastolic: 94,
      pulse: 82,
      temperature: 98.4,
      spo2: 98,
      weight: 74,
      height: 168,
      bmi: 26.2,
      bloodSugarRandom: 188,
    },
    riskCategory: 'moderate',
    assignedAshaId: 'usr-asha-1',
    registeredDate: '2026-01-15',
    familyMembers: [
      { id: 'fm-1', name: 'Sunita Patil', relationship: 'Spouse', age: 44, gender: 'female', abhaId: '91-4521-8890-1201' },
      { id: 'fm-2', name: 'Aniket Patil', relationship: 'Son', age: 19, gender: 'male', abhaId: '91-4521-8890-1202' },
      { id: 'fm-3', name: 'Tukaram Patil', relationship: 'Father', age: 76, gender: 'male', abhaId: '91-4521-8890-1203' },
    ],
  },
  {
    id: 'pat-102',
    abhaId: '91-8765-4321-9876',
    name: 'Kavita Sachin Gaikwad',
    nameMr: 'कविता सचिन गायकवाड',
    age: 24,
    gender: 'female',
    phone: '+91 97654 32109',
    address: 'Near Maruti Temple, Kolvan Road, Paud',
    village: 'Paud',
    taluka: 'Mulshi',
    district: 'Pune',
    pincode: '412108',
    bloodGroup: 'O+',
    allergies: [],
    chronicConditions: ['Severe Anemia (Hb 7.8 g/dL)', 'High-Risk Pregnancy (28 Weeks)'],
    emergencyContact: {
      name: 'Sachin Gaikwad',
      relationship: 'Husband',
      phone: '+91 97654 32110',
    },
    vitals: {
      bpSystolic: 138,
      bpDiastolic: 88,
      pulse: 92,
      temperature: 98.6,
      spo2: 97,
      weight: 52,
      height: 154,
      bmi: 21.9,
      hemoglobin: 7.8,
    },
    riskCategory: 'critical',
    assignedAshaId: 'usr-asha-1',
    registeredDate: '2025-11-20',
  },
  {
    id: 'pat-103',
    abhaId: '91-1122-3344-5566',
    name: 'Eknath Mahadev Shinde',
    nameMr: 'एकनाथ महादेव शिंदे',
    age: 62,
    gender: 'male',
    phone: '+91 94223 88776',
    address: 'Wadi Vasti, Paud Gaon',
    village: 'Paud',
    taluka: 'Mulshi',
    district: 'Pune',
    pincode: '412108',
    bloodGroup: 'A+',
    allergies: ['Aspirin'],
    chronicConditions: ['Ischemic Heart Disease', 'Mild COPD'],
    emergencyContact: {
      name: 'Vikas Shinde',
      relationship: 'Son',
      phone: '+91 94223 88777',
    },
    vitals: {
      bpSystolic: 154,
      bpDiastolic: 98,
      pulse: 76,
      temperature: 98.2,
      spo2: 95,
      weight: 68,
      height: 165,
      bmi: 25.0,
      bloodSugarRandom: 142,
    },
    riskCategory: 'high',
    assignedAshaId: 'usr-asha-1',
    registeredDate: '2026-02-01',
  },
  {
    id: 'pat-104',
    abhaId: '91-9988-7766-4433',
    name: 'Aarav Sachin Gaikwad',
    nameMr: 'आरव सचिन गायकवाड',
    age: 1,
    gender: 'male',
    phone: '+91 97654 32109',
    address: 'Near Maruti Temple, Kolvan Road, Paud',
    village: 'Paud',
    taluka: 'Mulshi',
    district: 'Pune',
    pincode: '412108',
    bloodGroup: 'O+',
    allergies: [],
    chronicConditions: [],
    emergencyContact: {
      name: 'Kavita Gaikwad',
      relationship: 'Mother',
      phone: '+91 97654 32109',
    },
    vitals: {
      pulse: 110,
      temperature: 98.4,
      weight: 9.2,
      height: 74,
    },
    riskCategory: 'normal',
    assignedAshaId: 'usr-asha-1',
    registeredDate: '2025-08-10',
  },
];

export const SEED_PRESCRIPTIONS = [
  {
    id: 'rx-2026-4401',
    consultationId: 'con-1001',
    patientId: 'pat-101',
    patientName: 'Ramesh Tukaram Patil',
    doctorId: 'usr-doc-1',
    doctorName: 'Dr. Rajesh Deshmukh (MBBS, DCH)',
    facilityName: 'PHC Paud, Mulshi',
    date: '2026-08-20',
    medicines: [
      {
        name: 'Amlodipine 5mg Tablets',
        genericName: 'Amlodipine Besylate 5mg',
        dosage: '5 mg',
        frequency: '1-0-0',
        duration: '30 days',
        instructions: 'Take 1 tablet every morning after breakfast with water.',
        instructionsMr: 'दररोज सकाळी नाश्त्यानंतर १ गोळी पाण्यासोबत घ्या.',
        instructionsHi: 'प्रतिदिन सुबह नाश्ते के बाद 1 गोली पानी के साथ लें।',
        timing: ['morning'],
        takeWith: 'after_food',
        quantity: 30,
      },
      {
        name: 'Metformin 500mg SR',
        genericName: 'Metformin Hydrochloride 500mg Sustained Release',
        dosage: '500 mg',
        frequency: '1-0-1',
        duration: '30 days',
        instructions: 'Take 1 tablet after breakfast and 1 tablet after dinner.',
        instructionsMr: 'सकाळी जेवणानंतर १ गोळी आणि रात्री जेवणानंतर १ गोळी घ्या.',
        instructionsHi: 'सुबह भोजन के बाद 1 गोली और रात के भोजन के बाद 1 गोली लें।',
        timing: ['morning', 'night'],
        takeWith: 'after_food',
        quantity: 60,
      },
      {
        name: 'Vitamin B-Complex with Zinc',
        genericName: 'B-Complex + Zinc Multivitamin',
        dosage: '1 capsule',
        frequency: '0-1-0',
        duration: '15 days',
        instructions: 'Take 1 capsule daily after lunch.',
        instructionsMr: 'दुपारी जेवणानंतर १ कॅप्सूल घ्या.',
        instructionsHi: 'दोपहर भोजन के बाद 1 कैप्सूल लें।',
        timing: ['afternoon'],
        takeWith: 'after_food',
        quantity: 15,
      },
    ],
    generalAdvice: 'Maintain low salt and low sugar diet. Brisk walk 30 minutes daily. Monitor blood pressure every week with ASHA worker Sunita.',
    generalAdviceMr: 'जेवणात मीठ आणि साखरेचे प्रमाण कमी ठेवा. दररोज ३० मिनिटे चाला. आशा सेविका सुनिता यांच्याकडून दर आठवड्याला बीपी तपासून घ्या.',
    generalAdviceHi: 'भोजन में नमक और चीनी की मात्रा कम रखें। प्रतिदिन 30 मिनट टहलें। आशा कार्यकर्ता से हर हफ्ते बीपी चेक करवाएं।',
    followUpDate: '2026-09-20',
    warnings: ['Avoid Penicillin based drugs due to recorded hypersensitivity.'],
  },
];
